# Make sure nvm and node (v8.9.3) is installed on server
# Symlink nvm bins to local bin because Ansible runs under sudo
# https://github.com/ansible/ansible/issues/29308
# sudo ln -s ~/.nvm/versions/node/v8.9.3/bin/nvm /usr/local/bin/nvm
# sudo ln -s ~/.nvm/versions/node/v8.9.3/bin/node /usr/local/bin/node

---
- hosts: production
  vars:
    project_path: /srv/www/staging.dxlab.sl.nsw.gov.au
    known_hosts:
      - name: github.com
        key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

  tasks:
    - name: Set some variable
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
        current_path: "{{ project_path }}/current"

    - name: Add known_hosts
      known_hosts:
        name: "{{ item.name }}"
        key: "{{ item.key | default(omit) }}"
        path: "{{ item.path | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      become: no
      with_items: "{{ known_hosts | default([]) }}"

    - name: Retrieve current release folder
      command: readlink -f current
      register: current_release_path
      ignore_errors: yes
      args:
        chdir: "{{ project_path }}"

    - name: Create new folder
      file:
        dest={{ release_path }}
        mode=0755
        recurse=yes
        state=directory

    - name: Clone the repository
      git:
        repo: git@github.com:slnsw/dxlab-website.git
        dest: "{{ release_path }}"

    - name: Copy .env
      copy:
        src: "../.env.production"
        dest: "{{ release_path }}/.env"
        # command: mv .env.production .env

    - name: Update npm
      # shell: npm i
      # environment:
      #   PATH: "~/.nvm/versions/node/v8.9.3/bin:{{ ansible_env.PATH }}"
      npm:
        path={{ release_path }}
        # executable="~/.nvm/versions/node/v8.9.3/bin/npm"
      # become: false

    - name: Update symlink
      file:
        src={{ release_path }}
        dest={{ current_path }}
        state=link

    - name: Delete old pm2 process
      command: pm2 delete dxlab-website
      ignore_errors: yes

    - name: Build app
      command: npm run build
      args:
        chdir: "{{ current_path }}"

    - name: Start pm2
      # command: pm2 start {{ current_path }}/server.js --name dxlab-website
      command: npm run start-pm2
      args:
        chdir: "{{ current_path }}"
